repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-vcs-permalinks
      - id: trailing-whitespace
        exclude: ^test/
      - id: mixed-line-ending
        exclude: ^test/

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.7
    hooks:
      - id: cargo-sort

  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.54
    hooks:
      - id: udeps

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --bins --tests --examples --all -- -D rust_2018_idioms -D warnings -W clippy::all -W clippy::cognitive_complexity # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [file, rust]
        # entry: cargo test --lib
        entry: cargo test
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

default_language_version:
  python: python3
